export const CHANNEL_CATEGORIES = [
  'Entertainment',
  'Political Party',
  'Sport',
  'School',
  'News',
  'Do It Yourself',
  'Adventures',
  'Social Group',
  'Comedy',
  'Drama',
  'Book Reading',
  'Non Governmental Organization',
  'Documentary',
  'Special Education',
  'Commentary',
  'Politics',
  'Satire',
  'Story Telling',
  'Digital Accessibility',
  'Reportage',
  'Public Education',
  'Home Remedy',
  'Variety',
  'Healthcare and Medicines',
  'Reviews',
  'True Life',
  'Poetry',
  'Crimes',
  'Analyses',
  'Magazine',
  'Courts and Constitution',
  'Science',
  'Fun Fact',
  'Religious',
  'Short Films',
  'Kiddies',
  'Finances',
  'Radio Shows',
  'Television Shows',
  'Inventions',
  'Culture and Traditions',
  'Artificial Intelligence',
  'Adverts and Promotions',
  'Gists and Gossips',
  'Information and Communication Technology',
  'Broadcast Media',
  'Movies',
  'Language',
  'Social Media',
  'Music',
  'Others',
] as const;

export const CHANNEL_LANGUAGES = [
  'English',
  'Yoruba',
  'Igbo',
  'Hausa',
  'French',
  'Spanish',
  'Arabic',
  'Chinese',
  'Swahili',
  'Pidgin',
  'Others',
] as const;

export type ChannelCategory = typeof CHANNEL_CATEGORIES[number];
export type ChannelLanguage = typeof CHANNEL_LANGUAGES[number];
